name: CICD Docker
on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: listing files
        run: ls -la
      
      # - name: Setup Go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: 1.21

      - name: Check Go Version
        run: go version

      - name: Run unit testing
        run: go test -v ./...
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: fakhriabdillah/goapp-docker:${{ github.run_number }}
      
  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
            docker pull fakhriabdillah/goapp-docker:${{ github.run_number }}
            docker rm -f goapp
            docker run --name goapp -d -p 80:8080 fakhriabdillah/goapp-docker:${{ github.run_number }}
