name: CICD Docker
on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: listing files
        run: ls -la
      - name: Run unit testing
        run: go test -v ./...